version: '3.8'

services:
  karina_api:
    build: ./api
    container_name: karina_api
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api/src/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - karina

  # karina_db:
  #   image: postgres:12.1-alpine
  #   container_name: karina_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - .env
  #   ports:
  #       - "127.0.0.1:5432:5432"
  #   networks:
  #     - karina

  # TODO: Cheack npm -v
  # karina_front:
  #   container_name: karina_front
  #   mem_limit: 300m
  #   build: ./front
  #   env_file:
  #     - .env
  #   depends_on: 
  #     - karina_api
  #   volumes:
  #     - site:/app/dist
  
  # karina_admin:
  #   container_name: karina_admin
  #   mem_limit: 300m
  #   build: ./admin-panel
  #   volumes:
  #     - admin:/app/dist
  #   depends_on: 
  #     - karina_front

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - site:/usr/share/nginx/html/site
      - admin:/usr/share/nginx/html/admin
    ports:
      - 80:80
    networks:
      - karina
    # depends_on: 
    #   - karina_admin

networks:
  karina:

volumes:
  site:
    driver: local 
  admin:
    driver: local 