version: '3.8'

services:
  karina_api:
    build: ./api
    container_name: karina_api
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api/src/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: .env

  karina_front:
    container_name: karina_front
    build: 
      context: ./front
      args:
        - VITE_API_HOSTNAME=${VITE_API_HOSTNAME}

    env_file: .env
    volumes:
      - site:/app/dist
  
  karina_admin:
    container_name: karina_admin
    build: ./admin-panel
    volumes:
      - admin:/app/dist
    depends_on: 
      - karina_front

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - site:/usr/share/nginx/html/site
      - admin:/usr/share/nginx/html/admin
    ports:
      - 80:80
    depends_on: 
      - karina_admin

volumes:
  site:
    driver: local 
  admin:
    driver: local 