export const cartId = 'c11589f2-ce86-4691-8953-111a33c4c3e8'
export const deleteFromCartUrl = '/delete_from_cart/?uuid='
export const addToCartUrl = '/add_to_cart/?uuid='
export const cartUrl = '/cart/?uuid='
export const getAllProductsUrl = '/get_all_products/'
